---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
    disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-registry.yaml

configMapGenerator:
- name: next-config
  namespace: ucandoit
  files:
      - next.config.js